### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Jingranxia** [JiehongLin/SAM-6D#15]
Hello, when I was running demo.sh, I encountered this error message. The environment for cv2 has already been installed

SAM-6D/SAM-6D/Render$ blenderproc run render_custom_templates.py --output_dir $OUTPUT_DIR --cad_path $CAD_PATH
Warning: Changed install path from /home_local/rodney... to /home/rodney..., there is no /home_local/ on this machine.
Using blender in /home/rodney/blender/blender-3.3.1-linux-x64
Using temporary directory: /dev/shm/blender_proc_b6ae4c30e8eb4d10a58d023f21318086
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Error: Python: Traceback (most recent call last):
  File "/home/rodney/rodney/SAM-6D/SAM-6D/Render/render_custom_templates.py", line 1, in <module>
    import blenderproc as bproc
  File "/home/rodney/.conda/envs/sam6d/lib/python3.9/site-packages/blenderproc/__init__.py", line 21, in <module>
    from .api import loader
  File "/home/rodney/.conda/envs/sam6d/lib/python3.9/site-packages/blenderproc/api/loader/__init__.py", line 1, in <module>
    from blenderproc.python.loader.AMASSLoader import load_AMASS
  File "/home/rodney/.conda/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/loader/AMASSLoader.py", line 15, in <module>
    from blenderproc.python.types.MeshObjectUtility import MeshObject
  File "/home/rodney/.conda/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/types/MeshObjectUtility.py", line 16, in <module>
    from blenderproc.python.utility.BlenderUtility import get_all_blender_mesh_objects
  File "/home/rodney/.conda/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/utility/BlenderUtility.py", line 12, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Error: script failed, file: 'render_custom_templates.py', exiting.
Cleaning temporary directory

**Comment by RocketMike98** [comment]
I guess you have to install opencv-python. If you have done so, maybe you haven't activated your virtual environment and don't have access to the installed packages. Try pip installing opencv-python or or conda activate sam6d and run again sh demo.sh

**Comment by Jingranxia** [comment]
> I guess you have to install opencv-python. If you have done so, maybe you haven't activated your virtual environment and don't have access to the installed packages. Try pip installing opencv-python or or conda activate sam6d and run again sh demo.sh

**Comment by Jingranxia** [comment]
> I guess you have to install opencv-python. If you have done so, maybe you haven't activated your virtual environment and don't have access to the installed packages. Try pip installing opencv-python or or conda activate sam6d and run again sh demo.sh

Hello author, I am certain that the environment has been activated and Pip has installed CV2, but this issue still exists

**Comment by foollh** [comment]
Sorry, we have not encountered this. It seems that blenderproc is not working correctly, perhaps you could try verifying that the command `blenderproc quickstart` works.

**Comment by muxiaoq** [comment]
I met this issue. 
I find the request.py in ~/anaconda3/env/.../urllib/request.py.
and add
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0'}

req = Request(fullurl, data, headers=headers)

it should be in around line 502. 

It seems like the issue could be done.
