### ISSUE TITLE
RuntimeError: CUDA error: Unkown error

### ISSUE THREAD

**Issue by guillermodecelisrodriguez** [JiehongLin/SAM-6D#18]
First thank you for sharing your amazing job!

I did not have any problem using demo.sh to obtain the same results as you, however, when trying the same demo.sh to inference on my own data, first i obtain the corresponding vis_ism.png image of the resulting mask, but when running the pose estimation model,  the next error appears:

=> creating model ...
load pre-trained checkpoint from: checkpoints/mae_pretrain_vit_base.pth
=> extracting templates ...
=> loading input data ...
=> running model ...
Traceback (most recent call last):
  File "/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 291, in <module>
    out = model(input_data)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py", line 32, in forward
    geo_embedding_m = self.geo_embedding(torch.cat([bg_point, sparse_pm], dim=1))
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 337, in forward
    d_embeddings = self.embedding(d_indices)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 280, in forward
    embeddings = torch.cat([sin_embeddings, cos_embeddings], dim=2)  # (-1, d_model/2, 2)
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I would really appreciate any help with this. Thanks in advance!!

**Comment by assia855** [comment]
Hi @guillermodecelisrodriguez  I'm struggling with thesame error. Did you find a solution please?

**Comment by guillermodecelisrodriguez** [comment]
hello @assia855 i did not find a solution yet, but if i do i will tell you :)

**Comment by JiehongLin** [comment]
We are sorry for the error. We have not encountered this problem with our machine.  

Maybe you can validate whether the variables, e.g., `sin_embeddings`, `cos_embeddings`,  `emb_indices` and  `self.div_term`, are on the same devices.

**Comment by yanshuangyingying** [comment]
> First thank you for sharing your amazing job!首先感谢您分享您的出色工作！
> 
> I did not have any problem using demo.sh to obtain the same results as you, however, when trying the same demo.sh to inference on my own data, first i obtain the corresponding vis_ism.png image of the resulting mask, but when running the pose estimation model, the next error appears:我使用 demo.sh 获得与您相同的结果没有任何问题，但是，当尝试相同的 demo.sh 对我自己的数据进行推理时，首先我获得了结果掩码的相应vis_ism.png图像，但是当运行姿态估计模型时，会出现下一个错误：
> 
> => creating model ...  => 正在创建模型 ... load pre-trained checkpoint from: checkpoints/mae_pretrain_vit_base.pth从以下位置加载预训练的检查点： checkpoints/mae_pretrain_vit_base.pth => extracting templates ...=> 正在提取模板... => loading input data ...=> 正在加载输入数据... => running model ...  => 跑步模特 ... Traceback (most recent call last):回溯 （最近调用最后）： File "/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 291, in 文件“/SAM-6D/Pose_Estimation_Model/run_inference_custom.py”，第 291 行，在 out = model(input_data)  out = 模型 （input_data） File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl文件“/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1501 行，_call_impl return forward_call(*args, **kwargs)返回 forward_call（*args， **kwargs） File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py", line 32, in forward文件 “/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py“，第 32 行，向前 geo_embedding_m = self.geo_embedding(torch.cat([bg_point, sparse_pm], dim=1))geo_embedding_m = self.geo_embedding（torch.cat（[bg_point， sparse_pm]， dim=1）） File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl文件“/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1501 行，_call_impl return forward_call(*args, **kwargs)返回 forward_call（*args， **kwargs） File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 337, in forward文件 “/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py“，第 337 行，向前 d_embeddings = self.embedding(d_indices)d_embeddings = self.embedding（d_indices） File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl文件“/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py”，第 1501 行，_call_impl return forward_call(*args, **kwargs)返回 forward_call（*args， **kwargs） File "/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 280, in forward文件 “/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py“，第 280 行，向前输入 embeddings = torch.cat([sin_embeddings, cos_embeddings], dim=2) # (-1, d_model/2, 2)嵌入 = torch.cat（[sin_embeddings， cos_embeddings]， dim=2） # （-1， d_model/2， 2） RuntimeError: CUDA error: unknown errorRuntimeError： CUDA 错误：未知错误 CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.CUDA 内核错误可能会在其他一些 API 调用中异步报告，因此下面的堆栈跟踪可能不正确。 For debugging consider passing CUDA_LAUNCH_BLOCKING=1.对于调试，请考虑传递 CUDA_LAUNCH_BLOCKING=1。 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.使用 `TORCH_USE_CUDA_DSA` 进行编译以启用设备端断言。
> 
> I would really appreciate any help with this. Thanks in advance!!我真的很感激任何帮助。提前感谢！！

hello,I meet cuda out of meory,but my device is rtx4090 24G,What is your device?
