### ISSUE TITLE
Pose Estimation Model OOM

### ISSUE THREAD

**Issue by fedona** [JiehongLin/SAM-6D#24]
Hello, I am trying to run SAM6D on a RTX 2080 with 8GB of memory. The demo dataset works fine, but the Pose Estimation Model goes OOM every time I try my cad model as input. It does not matter how many template poses I feed him, it fails even if I give one alone.

Is there a specific part of the code that i can tweak in order to make it  (possibly) run on my limited set? Thanks!

**Comment by JiehongLin** [comment]
Could you please specify which step in the process would lead to an out-of-memory issue?

**Comment by Lokesh-26** [comment]
Hello @JiehongLin,
   I am facing the same issue. My dataset are bigger objects used in warehousing. eg: Pallet, small containers (KLT). 
   My datasets are **texture-less**
   

- ###  Instance Segmentation inference script. 

 ```
 Traceback (most recent call last):
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 218, in <module>
    run_inference(
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 181, in run_inference
    image_uv = model.project_template_to_image(best_template, pred_idx_objects, batch, detections.masks)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/detector.py", line 221, in project_template_to_image
    translate = self.Calculate_the_query_translation(proposals, batch["depth"][0], batch["cam_intrinsic"][0], batch['depth_scale'])
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/detector.py", line 243, in Calculate_the_query_translation
    translate = depth_image_to_pointcloud_translate_torch(
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/utils/trimesh_utils.py", line 92, in depth_image_to_pointcloud_translate_torch
    X = (u - K[0, 2]) * Z / K[0, 0]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 11.90 GiB total capacity; 8.20 GiB already allocated; 109.69 MiB free; 11.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I solved the error by changing the **depth** and **scale** from `float64 to float32` in the [trimesh_utils.py ](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/Instance_Segmentation_Model/utils/trimesh_utils.py)script to reduce the memory usage. I am not sure if this is the correct way to do it. It might lead to inaccuracy. Please suggest if there any other better solution.
 

- ### Pose Estimation inference script.  

```
 Traceback (most recent call last):
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 297, in <module>
    out = model(input_data)
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py", line 32, in forward
    geo_embedding_m = self.geo_embedding(torch.cat([bg_point, sparse_pm], dim=1))
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 343, in forward
    a_embeddings = self.embedding(a_indices)
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 281, in forward
    sin_embeddings = torch.sin(omegas)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.72 GiB (GPU 0; 11.90 GiB total capacity; 7.13 GiB already allocated; 3.30 GiB free; 8.00 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I tried to change the datatype of **emb_indices** and **omegas** from `float32 to float16` in the [transformer.py](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/Pose_Estimation_Model/model/transformer.py) script. It solved the CUDA out of memory issue but resulted in the following error. 

```
Traceback (most recent call last):
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 297, in <module>
    out = model(input_data)
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py", line 32, in forward
    geo_embedding_m = self.geo_embedding(torch.cat([bg_point, sparse_pm], dim=1))
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/transformer.py", line 341, in forward
    d_embeddings = self.proj_d(d_embeddings)
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
```

Please guide me with the above issues. Thanks in advance. 

I am also facing another issue to render larger objects. I will create another issue to avoid confusion. 

I tried my best to keep it clear. If anything is unclear please let me know.

**Comment by Lokesh-26** [comment]
I found the solution. I tuned the parameters of SAM 

(https://github.com/JiehongLin/SAM-6D/blob/b1ba7e9082c93e5fbe55d4cbfd5b6d18768cd133/SAM-6D/Instance_Segmentation_Model/segment_anything/automatic_mask_generator.py#L39-L40)

**Comment by kevinDrawn** [comment]
@Lokesh-26  What is your graphic card memory ?  And How much inference time does it take per image?

**Comment by Lokesh-26** [comment]
1. Sorry, I didn't notice the inference time. 
2. I lowered points_per_side = 6
And points_per_batch = 2.

**Comment by kevinDrawn** [comment]
Thank you!
