### ISSUE TITLE
Error: StructRNA of type Material has been removed

### ISSUE THREAD

**Issue by Lokesh-26** [JiehongLin/SAM-6D#25]
Hello, 
My dataset are bigger objects used in warehousing. eg: Pallet, small containers (KLT) and they are texture-less.

The render script is working fine for some objects. I am facing the following issues for few objects: 

```
Warning: Changed install path from /home_local/gouda... to /home/gouda..., there is no /home_local/ on this machine.
Using blender in /home/gouda/blender/blender-3.5.1-linux-x64
Using temporary directory: /dev/shm/blender_proc_18333dbbd3934aa29c62eb0ada41cdab
Blender 3.5.1 (hash e1ccd9d4a1d3 built 2023-04-24 23:31:15)
/home/gouda/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/gouda/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/gouda/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:500: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/gouda/blender/blender-3.5.1-linux-x64/3.5/python/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Selecting render devices...
Device NVIDIA TITAN Xp of type OPTIX found and used.
Device NVIDIA TITAN Xp of type OPTIX found and used.
Device Intel Core i9-7940X CPU @ 3.10GHz of type CPU found and used.

Successfully imported '/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Data/Example/big_robots_6d/pallet.ply' in 0.004 sec
Rendering 1 frames of colors...
Finished rendering after 0.851 seconds
Rendering 1 frames of nocs...
Finished rendering after 0.082 seconds

Successfully imported '/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Data/Example/big_robots_6d/pallet.ply' in 0.012 sec
Warning! Detected output entries with duplicate keys and paths
Rendering 1 frames of colors...
Finished rendering after 0.667 seconds
Error: Python: Traceback (most recent call last):
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Render/render_custom_templates.py", line 79, in <module>
    data.update(bproc.renderer.render_nocs())
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/renderer/NOCSRendererUtility.py", line 35, in render_nocs
    with UndoAfterExecution():
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/utility/Utility.py", line 487, in __enter__
    self.struct_instances = get_instances()
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/types/StructUtilityFunctions.py", line 22, in get_instances
    instances.append((instance.get_name(), instance))
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/types/StructUtility.py", line 50, in get_name
    return self.blender_obj.name
ReferenceError: StructRNA of type Material has been removed

Error: script failed, file: 'render_custom_templates.py', exiting.
Cleaning temporary directory
```

It renders one frame and then throws an error. Please help me to solve the error and If you need further information please let me know.

**Comment by foollh** [comment]
Sorry, it seems like the problem of `blenderproc`. Someone has the same [issue](https://github.com/DLR-RM/BlenderProc/issues/547) in `blenderproc`. Hoping it can help you.

**Comment by kevinDrawn** [comment]
@Lokesh-26  Hello! How can you solve this problem??

**Comment by Lokesh-26** [comment]
@kevinDrawn , I have not solved it yet.Since,  some of my other objects are working fine.

**Comment by kevinDrawn** [comment]
I recently found another way to solve it. 

This error occured when the model is simple. ex) box

I expereinced this error whenever the simple shape model put in the Blenderbroc.

So, I edited the model to make the characteristic.

![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/49db7afe-91d2-4419-828a-d3276bea01dd)

It is my original CAD Model. It is simple shape. 

So I carved the shape which drawed by free curve in solidworks.

![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/a0615dd3-e2b7-42a6-9544-b887dfc431c0)

Eventually, It is work.

![image](https://github.com/JiehongLin/SAM-6D/assets/128012358/59d8a62e-1caf-4a0b-a49d-23b0862e1a82)

**Comment by Lokesh-26** [comment]
@kevinDrawn thanks a lot for sharing the solution. I'll try the method you did.

**Comment by Lokesh-26** [comment]
@kevinDrawn , I directly imported the ply file in blender and added a modifier to the object. It worked!!!. :)

**Comment by kevinDrawn** [comment]
Nice~~!
