### ISSUE TITLE
ERROR: Empty array in ISM inference script

### ISSUE THREAD

**Issue by Lokesh-26** [JiehongLin/SAM-6D#27]
Hello, 

 My datasets are in BOP format. I render all my models from [render_bop_templates.py
](https://github.com/JiehongLin/SAM-6D/blob/fca43b6aa9effa8b6aea59a5cf8bf91014cfa558/SAM-6D/Render/render_bop_templates.py). When I [run_inference.py](https://github.com/JiehongLin/SAM-6D/blob/fca43b6aa9effa8b6aea59a5cf8bf91014cfa558/SAM-6D/Instance_Segmentation_Model/run_inference.py). I get the following error. 
```
media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/bin/python /media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference.py 
INFO:pytorch_lightning.utilities.rank_zero:ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
INFO:pytorch_lightning.utilities.rank_zero:Using 16bit native Automatic Mixed Precision (AMP)
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:IPU available: False, using: 0 IPUs
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
INFO:lightning_lite.utilities.seed:Global seed set to 2023
INFO:lightning_lite.utilities.seed:Global seed set to 2023
Loading metaData: 100%|██████████| 2/2 [00:00<00:00, 154.45it/s]
Loading metaData: 100%|██████████| 1/1 [00:00<00:00, 81.16it/s]
Finding nearest rendering close to template poses:   0%|          | 0/10 [00:00<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference.py", line 83, in <module>
    run_inference()
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/media/gouda/3C448DDD448D99F2/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference.py", line 63, in run_inference
    ref_dataset.load_processed_metaData(reset_metaData=True)
  File "/media/gouda/3C448DDD448D99F2/segmentation/SAM-6D/SAM-6D/Instance_Segmentation_Model/provider/bop_pbr.py", line 177, in load_processed_metaData
    selected_index_obj = np.random.choice(selected_index_obj, 5000)
  File "numpy/random/mtrand.pyx", line 951, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Please help me with the following issue.

**Comment by Lokesh-26** [comment]
For some reason, even though some objects are present in the frame it is not detected. So I skipped the loop if no obj_id is found.
