### ISSUE TITLE
Regarding errors in loading the Sam6d model

### ISSUE THREAD

**Issue by Jingranxia** [JiehongLin/SAM-6D#29]
作者您好，我copy了您的docker，然而在跑demo.sh的时候，姿态估计程序遇到了如下问题，能否帮忙解答一下，不胜感激！

Traceback (most recent call last):
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 266, in <module>
    model = MODEL.Net(cfg.model)
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/pose_estimation_model.py", line 18, in __init__
    self.feature_extraction = ViTEncoder(cfg.feature_extraction, self.fine_npoint)
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/feature_extraction.py", line 126, in __init__
    self.rgb_net = ViT_AE(cfg)
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/../Pose_Estimation_Model/model/feature_extraction.py", line 83, in __init__
    model_zoo.load_url('https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_'+ self.vit_type +'.pth', 'checkpoints')
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Jingranxia** [comment]
权重文件通过 download_sam6d-pem.py 得到

**Comment by foollh** [comment]
Thank you for your reminder. It seems like the pretrained mae backbone failed to download. You can change the `model.feature_extraction.pre-trained` to `False` in [base. yaml](https://github.com/JiehongLin/SAM-6D/blob/main/SAM-6D/Pose_Estimation_Model/config/base.yaml) to avoid downloading it.
