### ISSUE TITLE
Problems encountered in pose inference process

### ISSUE THREAD

**Issue by Jingranxia** [JiehongLin/SAM-6D#30]
作者您好，我又遇到一个问题，我用自己的数据替换了demo的数据，在sam部分执行的非常好，然而在pose预测的过程中出现了问题，这个问题应该是什么问题呢？

load pre-trained checkpoint from: checkpoints/mae_pretrain_vit_base.pth
=> extracting templates ...
=> loading input data ...
Traceback (most recent call last):
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 279, in <module>
    input_data, img, whole_pts, model_points, detections = get_test_data(
  File "/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 246, in get_test_data
    ret_dict['pts'] = torch.stack(all_cloud).cuda()
RuntimeError: stack expects a non-empty TensorList

**Comment by Jingranxia** [comment]
问题解决了，scale改成0.0001即可

**Comment by kevinDrawn** [comment]
product 1000 to your original depth scale.
