### ISSUE TITLE
blenderproc run error

### ISSUE THREAD

**Issue by liuchangji** [JiehongLin/SAM-6D#52]
When I run demo.sh and input below:

>  blenderproc run render_custom_templates.py --output_dir $OUTPUT_DIR --cad_path $CAD_PATH #--colorize True 

it occured a error immediately.
Is that a network problem or ? The log is below.
```
Warning: Changed install path from /home_local/lcj... to /home/lcj..., there is no /home_local/ on this machine.
Downloading blender from https://download.blender.org/release/Blender3.3/blender-3.3.1-linux-x64.tar.xz
Traceback (most recent call last):
  File "/home/lcj/anaconda3/envs/sam6d/bin/blenderproc", line 8, in <module>
    sys.exit(cli())
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/command_line.py", line 149, in cli
    blender_run_path, major_version = InstallUtility.make_sure_blender_is_installed(custom_blender_path,
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/utility/InstallUtility.py", line 179, in make_sure_blender_is_installed
    raise e
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/site-packages/blenderproc/python/utility/InstallUtility.py", line 163, in make_sure_blender_is_installed
    file_tmp = urlretrieve(url, None, DownloadProgressBar())[0]
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/lcj/anaconda3/envs/sam6d/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```

**Comment by liuchangji** [comment]
fixed by [https://blender.stackexchange.com/questions/306267/blenderproc-quickstart-urllib-error-httperror-http-error-403-forbidden](url)

**Comment by zhangsong1213** [comment]
try https://github.com/JiehongLin/SAM-6D/issues/97
