### ISSUE TITLE
How to run the docker image

### ISSUE THREAD

**Issue by Zialo** [JiehongLin/SAM-6D#57]
Hi!

First of all, thank you very much for the work done, it is very interesting.

I am trying to run the docker image but having zero knowledge in docker, I am not able to do it. I have the image after the pull but when I do the run it tells me that there is no command specified. What can I do?

Thank you in advance!

KR

**Comment by grth25** [comment]
Same here, did you find a solution?

**Comment by 3114917790** [comment]
> 同样在这里，你找到解决方案了吗？
I solved it using docker

**Comment by Zialo** [comment]
> > 同样在这里，你找到解决方案了吗？
> > I solved it using docker

My goodness, I hadn't thought of using Docker to run a Docker image (completely ironic)

**Comment by 3114917790** [comment]
> I hadn't thought of using Docker to run a Docker image (completely ironic)

With docker, you can execute sh files directly and save a lot of things

**Comment by OxygenIsland** [comment]
docker run -it  lihualiu/sam-6d:1.0 bash

**Comment by Rasula404** [comment]
Hello I am able to run this command and access the container @OxygenIsland. But I cant see any files belonging to the repo. The owners have not done a good job of how we can use the docker image to get the repo. Can you please help me on how I can actually use it?

**Comment by ron007d** [comment]
1. Docker pull
2. run docker
```bash
docker run -it <image_name>:<tag> /bin/bash
```
3. you will get `(base) root@something:/`
4. acticate sam6d conda
```bash
conda activate sam6d
```
5. change directory to workspace
```bash
cd workspace
```
6. git clone the code the do as give 
7. in the path use full path
```bash
export CAD_PATH=$PWD/Data/Example/obj_000005.ply    # path to a given cad model(mm)
export RGB_PATH=$PWD/Data/Example/rgb.png           # path to a given RGB image
export DEPTH_PATH=$PWD/Data/Example/depth.png       # path to a given depth map(mm)
export CAMERA_PATH=$PWD/Data/Example/camera.json    # path to given camera intrinsics
export OUTPUT_DIR=$PWD/Data/Example/outputs         # path to a pre-defined file for saving results
```

**Comment by nickcharron** [comment]
@ron007d I'm curious if this docker needs a GPU to run the above code? When following your steps above, I'm getting this error which I think is due to not having access to a GPU in docker:

```Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 224, in <module>
    run_inference(
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 154, in run_inference
    model.ref_data["descriptors"] = model.descriptor_model.compute_features(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/dinov2.py", line 150, in compute_features
    features = self.forward_by_chunk(images)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/dinov2.py", line 163, in forward_by_chunk
    feats = self.compute_features(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/dinov2.py", line 152, in compute_features
    features = self.model(images)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/vision_transformer.py", line 321, in forward
    ret = self.forward_features(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/vision_transformer.py", line 257, in forward_features
    x = blk(x)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/layers/block.py", line 247, in forward
    return super().forward(x_or_x_list)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/layers/block.py", line 105, in forward
    x = x + attn_residual_func(x)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/layers/block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/layers/attention.py", line 76, in forward
    x = memory_efficient_attention(q, k, v, attn_bias=attn_bias)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 294, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/xformers/ops/fmha/dispatch.py", line 98, in _dispatch_fw
    return _run_priority_list(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/xformers/ops/fmha/dispatch.py", line 73, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(16, 257, 16, 64) (torch.float32)
     key         : shape=(16, 257, 16, 64) (torch.float32)
     value       : shape=(16, 257, 16, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 64
Traceback (most recent call last):
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 1798, in _LoadNvmlLibrary
    nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/opt/conda/envs/sam6d/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file too short
```

**Comment by VeeranjaneyuluToka** [comment]
I pulled docker image as below

docker pul lihualiu/sam-6d:1.0
docker run --rm -it lihualiu/sam-6d:1.0

when i try to run demo.sh, it shows that

No model named torch and gorilla.

I believe it should work smoothly with docker image, is not it? or am i missing anything here?

**Comment by ron007d** [comment]
> I pulled docker image as below
> 
> docker pul lihualiu/sam-6d:1.0 docker run --rm -it lihualiu/sam-6d:1.0
> 
> when i try to run demo.sh, it shows that
> 
> No model named torch and gorilla.
> 
> I believe it should work smoothly with docker image, is not it? or am i missing anything here?

activate conda env then run this

**Comment by 3114917790** [comment]
> 我拉取了 docker 镜像，如下所示
> 
> docker pul lihualiu/sam-6d：1.0 docker run --rm -it lihualiu/sam-6d：1.0
> 
> 当我尝试运行 demo.sh 时，它显示
> 
> 没有名为 torch 和 gorilla 的模型。
> 
> 我相信它应该可以与 docker 镜像顺利配合，不是吗？还是我在这里遗漏了什么？
you should activate when you bash it

**Comment by radhenborgrobotic** [comment]
I am facing a similar issue as mentioned above. I pulled the docker run, ran the docker container, activated the conda env, and set the environment variables. Setting the environment variable for the example data files is not working has expected. Had to modify the path based on the error I was getting after running demo.sh. 

After that I run the demo.sh script again and I get the following error. Has anyone been able to run the the demo in the docker image? Isn't the whole point of docker image that the code should just work out of the box? Am i missing some installation steps. I'd really appreciate if the author of this repo can provide suggestions on how to fix this issue.

```
/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'ISM_sam.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
INFO:root:Initializing model
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpus24d7bo
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpus24d7bo/_remote_module_non_scriptable.py
INFO:root:Loading SAM model from ./checkpoints/segment-anything/
Traceback (most recent call last):
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/model/sam.py", line 26, in load_sam
    sam = sam_model_registry[model_type](
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/segment_anything/build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/segment_anything/build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/segment-anything/sam_vit_h_4b8939.pth'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 224, in <module>
    run_inference(
  File "/workspace/SAM-6D/SAM-6D/Instance_Segmentation_Model/run_inference_custom.py", line 110, in run_inference
    model = instantiate(cfg.model)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'model.sam.load_sam':
FileNotFoundError(2, 'No such file or directory')
full_key: model.segmentor_model.sam
Traceback (most recent call last):
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 1798, in _LoadNvmlLibrary
    nvmlLib = CDLL("libnvidia-ml.so.1")
  File "/opt/conda/envs/sam6d/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: file too short

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 1, in <module>
    import gorilla
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/gorilla/__init__.py", line 4, in <module>
    from .utils import *
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/gorilla/utils/__init__.py", line 5, in <module>
    from .gpu import (get_free_gpu, set_cuda_visible_devices)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/gorilla/utils/gpu.py", line 13, in <module>
    pynvml.nvmlInit()
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 1770, in nvmlInit
    nvmlInitWithFlags(0)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 1753, in nvmlInitWithFlags
    _LoadNvmlLibrary()
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 1800, in _LoadNvmlLibrary
    _nvmlCheckReturn(NVML_ERROR_LIBRARY_NOT_FOUND)
  File "/opt/conda/envs/sam6d/lib/python3.9/site-packages/pynvml/nvml.py", line 833, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
```

**Comment by radhenborgrobotic** [comment]
I managed to run the ./demo.sh form within the docker container. Message me if you want to know the steps I followed.

**Comment by LiuVuitton** [comment]
> I managed to run the ./demo.sh form within the docker container. Message me if you want to know the steps I followed.

Hi, I had the same exact issues you had in your previous message while using the docker image.
Can I ask you how you managed to fix it?

**Comment by radhenborgrobotic** [comment]
@LiuVuitton check these instructions out, that have worked for me. 


## Steps for the initial setup

Run this original docker image 
```
docker run --gpus all -it --rm --name sam6d_gpu -v $(pwd):/workspace lihualiu/sam-6d:1.0 bash
```

From inside the docker container, activate the conda env
```
conda activate sam6d
```

Clone the repo
```
git clone https://github.com/JiehongLin/SAM-6D.git
```

Go inside the folder
```
cd SAM-6D/SAM-6D
```

Set path for files
```
export CAD_PATH=$PWD/Data/Example/obj_000005.ply
export RGB_PATH=$PWD/Data/Example/rgb.png
export DEPTH_PATH=$PWD/Data/Example/depth.png
export CAMERA_PATH=$PWD/Data/Example/camera.json
export OUTPUT_DIR=$PWD/Data/Example/outputs
```

Download ISM pretrained model
```
cd Instance_Segmentation_Model
python download_sam.py
python download_fastsam.py
python download_dinov2.py
cd ../
```

Download PEM pretrained model
```
cd Pose_Estimation_Model
python download_sam6d-pem.py
```

FINALLY RUN THE DEMO
```
chmod +x demo.sh
./demo.sh
```
