### ISSUE TITLE
ValueError: string is not a file: Data/Example/obj_000005.ply

### ISSUE THREAD

**Issue by goddard73** [JiehongLin/SAM-6D#66]
`(sam6d) goddard@Goddard-Wen:/mnt/c/Users/TT/Desktop/SAM-6D-main/SAM-6D$ sh demo.sh
Warning: Changed install path from /home_local/goddard... to /home/goddard..., there is no /home_local/ on this machine.
Using blender in /home/goddard/blender/blender-3.3.1-linux-x64
Using temporary directory: /dev/shm/blender_proc_dc9eab73c1024ebaa1246e1599794c82
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
/run/user/1000/gvfs/ non-existent directory
Selecting render devices...
Device NVIDIA GeForce GTX 1660 Ti of type CUDA found and used.
Device Intel Core i7-9750H CPU @ 2.60GHz of type CPU found and used.
Error: Python: Traceback (most recent call last):
  File "/mnt/c/Users/TT/Desktop/SAM-6D-main/SAM-6D/Render/render_custom_templates.py", line 42, in <module>
    scale = get_norm_info(args.cad_path)
  File "/mnt/c/Users/TT/Desktop/SAM-6D-main/SAM-6D/Render/render_custom_templates.py", line 24, in get_norm_info
    mesh = trimesh.load(mesh_path, force='mesh')
  File "/home/goddard/blender/blender-3.3.1-linux-x64/custom-python-packages/lib/python3.10/site-packages/trimesh/exchange/load.py", line 116, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/home/goddard/blender/blender-3.3.1-linux-x64/custom-python-packages/lib/python3.10/site-packages/trimesh/exchange/load.py", line 630, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: Data/Example/obj_000005.ply

Error: script failed, file: 'render_custom_templates.py', exiting.
Cleaning temporary directory
/home/goddard/anaconda3/envs/sam6d/lib/python3.9/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'ISM_sam.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
`
尝试运行代码的时候出现如上错误，我觉得是因为图片没被成功使用所以后面的ISM_sam.yaml才会报错，但是图片为什么没有被成功使用

**Comment by WMAAA** [comment]
因为文件路径问题，,https://github.com/JiehongLin/SAM-6D/issues/32#issuecomment-2023113901中提供的fork，`export`后的文件路径，有`$PWD`

**Comment by WMAAA** [comment]
我运行demo成功了，但是不会运行自己的数据，而且这个要用CAD模型

**Comment by goddard73** [comment]
谢谢，我跟着你的链接解决了问题
![3](https://github.com/user-attachments/assets/b6783963-1761-4906-ad84-371d65bbea91)
这是我使用的命令，还要再提一点，在win文件资源管理器中与SAM-6D同级可能会出现Data文件夹，如果有，删掉然后再次尝试运行

**Comment by goddard73** [comment]
谢谢，我跟着你的链接解决了问题 @WMAAA 
![3](https://github.com/user-attachments/assets/56a3fc88-32bb-4451-aa03-20bcf04a73cf)
这是我使用的命令，值得注意的是，在win文件资源管理器中打开项目可能会发现存在一个Data文件夹与SAM-6D同级，把他删掉然后重新尝试运行

我使用的是win11+wsl Ubuntu

**Comment by WMAAA** [comment]
> 谢谢，我跟着你的链接解决了问题 ![3](https://private-user-images.githubusercontent.com/170693827/363199801-56a3fc88-32bb-4451-aa03-20bcf04a73cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTAzMDksIm5iZiI6MTcyNTA5MDAwOSwicGF0aCI6Ii8xNzA2OTM4MjcvMzYzMTk5ODAxLTU2YTNmYzg4LTMyYmItNDQ1MS1hYTAzLTIwYmNmMDRhNzNjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwNzQwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDEwMzhkNWIxOTQ0ODY1NzQ2MDdhODVlNGQ3MjgzNjRiYmU0OWUwODlmZTMzMjc0OTQ0MDMzYTAxNjFkMTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ttT08JTaDORSZZX8ijMiMG5n31ipzwMIhdi7Uhqu-w) 这是我使用的命令，值得注意的是，在win文件资源管理器中打开项目可能会发现存在一个Data文件夹与SAM-6D同级，把他删掉然后重新尝试运行
> 
> 我使用的是win11+wsl Ubuntu

如何使用视频进行跟踪，你尝试了吗

**Comment by WMAAA** [comment]
如何使用视频进行跟踪，你尝试了吗
