### ISSUE TITLE
AttributeError: module 'gorilla' has no attribute 'Config'

### ISSUE THREAD

**Issue by ksky0222** [JiehongLin/SAM-6D#75]
I ran demo.sh, but an error occurred, and when I checked the attributes of gorilla(0.4.0), I found that there really is no Config. What should I do?

error log:
Traceback (most recent call last):
  File "/home/airlab/IsaacLab/source/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 258, in <module>
    cfg = init()
  File "/home/airlab/IsaacLab/source/SAM-6D/SAM-6D/Pose_Estimation_Model/run_inference_custom.py", line 67, in init
    cfg = gorilla.Config.fromfile(args.config)
AttributeError: module 'gorilla' has no attribute 'Config'

**Comment by ksky0222** [comment]
I solved it

pip uninstall gorilla
pip install gorilla-core
